### ISSUE TITLE
""" Creates symlink from env in tmp basedir to environment in ultimate basedir. """

### ISSUE THREAD

**Issue by seanodea** [dashcheulov/r10k-webhook#2]
Why?

Why would you move the yaml code to a temp dir and then symlink the realdir to the temp dir? I don't think it's a good strategy.

**Comment by seanodea** [comment]
I just wanna run r10k when the webhook is hit, I don't want any method of doing that changing my paths or creating symlinks.

**Comment by dashcheulov** [comment]
This layer is used for mapping branches to environments' names. For example, if you want branch 'master' to be named as env 'production', you have to rename dir 'master' provided by r10k to 'production'. Then puppet will use that name as name of environment.
